#!/bin/bash
TARGET="/home/ubuntu/wedding/deploy-folder"
GIT_DIR="/home/ubuntu/wedding/prod-git"
BRANCH="main"
export PATH=$PATH:/home/ubuntu/n/bin

while read oldrev newrev ref
do
        # only checking out the master (or whatever branch you would like to deploy)
        if [ "$ref" = "refs/heads/$BRANCH" ];
        then
                echo "Ref $ref received. Deploying ${BRANCH} branch to production..."
                /home/ubuntu/n/bin/pm2 stop all
                rm -rf /home/ubuntu/wedding/deploy-folder/*
                git --work-tree=$TARGET --git-dir=$GIT_DIR checkout -f $BRANCH
                cd /home/ubuntu/wedding/deploy-folder/server
                npm ci >> out.txt
                cd /home/ubuntu/wedding/deploy-folder/svelte-vite/
                npm ci >> out.txt
                npm run build >> out.txt
                ln -s /home/ubuntu/wedding/_pictures /home/ubuntu/wedding/deploy-folder/svelte-vite/dist/static_pictures
                cp /home/ubuntu/wedding/.env /home/ubuntu/wedding/deploy-folder/server/
                /home/ubuntu/n/bin/pm2 restart /home/ubuntu/wedding/deploy-folder/server/server.js
        else
                echo "Ref $ref received. Doing nothing: only the ${BRANCH} branch may be deployed on this server."
        fi
done
